site_name: Sea Forward Documentation
docs_dir: docs
theme:
  name: material
  logo: assets/logo.webp
  features:
    - navigation.expand
    - navigation.top  
    - navigation.instant
    - content.code.copy
    - navigation.footer
  palette:
    # Mode sombre (Slate)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Mode clair (Default)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

#extra:
#  social:
#    - icon: material/file-pdf-box
#      link: /pdf/documentation.pdf
#      name: Télécharger en PDF

extra_css:
  - css/syntax_custom.css
  - css/extra.css

plugins:
  #- with-pdf:
  #    output_path: pdf/documentation.pdf
  #    cover_title: "Sea Forward Documentation"
  #    cover_subtitle: "Data Download Guide"
  #    author: "Opera SeaForward Team"
  #    toc_level: 2
  #    enabled_if_env: ENABLE_PDF
  #- print-site:
  #    add_to_navigation: true
  #    print_page_title: "Télécharger en PDF"
  #    print_page_description: "Exporter cette page en PDF"
  #    enabled_if_env: ENABLE_PRINT
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - material/search:
      highlight: true
      highlight_threshold: 2

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true          # affiche les numéros de ligne
      #anchor_linenums: true   # permet de cibler une ligne précise
      use_pygments: true      # utilise Pygments pour la coloration
  - pymdownx.superfences      # gère les blocs imbriqués et les langages multiples
  - pymdownx.inlinehilite     # coloration inline avec `==code==`
  - pymdownx.snippets         # inclure des extraits externes
  - pymdownx.extra            # ajoute des fonctionnalités utiles
  - pymdownx.details          # permet de créer des blocs repliables (accordéons)
  - pymdownx.tabbed           # permet de créer des onglets pour organiser le contenu

nav:
  - Home: index.md
  - Hands-on Documentation: handsOn.md
  - Setup (from a bare machine to build-ready): 01_setup.md
  - Building a Forecast Configuration — Hand-Edit Edition: 02_forecast_config.md
  - Running a Forecast: 03_forecast.md
  - Building and Running a Hindcast — Hand-Edit Edition: 04_hindcast.md