site_name: Sea Forward Documentation
docs_dir: docs
theme:
  name: material
  logo: assets/logo.webp
  features:
    - navigation.expand
    - content.code.copy
    - navigation.footer
  palette:
    # Mode sombre (Slate)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Mode clair (Default)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

#extra:
#  social:
#    - icon: material/file-pdf-box
#      link: /pdf/documentation.pdf
#      name: Télécharger en PDF

extra_css:
  - css/syntax_custom.css
  - css/extra.css

plugins:
  #- with-pdf:
  #    output_path: pdf/documentation.pdf
  #    cover_title: "Sea Forward Documentation"
  #    cover_subtitle: "Data Download Guide"
  #    author: "Opera SeaForward Team"
  #    toc_level: 2
  #    enabled_if_env: ENABLE_PDF
  #- print-site:
  #    add_to_navigation: true
  #    print_page_title: "Télécharger en PDF"
  #    print_page_description: "Exporter cette page en PDF"
  #    enabled_if_env: ENABLE_PRINT
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - material/search:
      highlight: true
      highlight_threshold: 2
  - with-pdf:
 #     pdf_button_text: "📘 Télécharger PDF"
      cover: true
      cover_title: "Sea Forward Documentation"
      cover_subtitle: "Version 1.0"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - codehilite:
      guess_lang: false
      use_pygments: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
  #- Introduction: introduction.md
  #- Détails du script: script.md